# Publishes docker image, pinning actions to a commit SHA,
# and updating most recently built image with the latest tag.
# Can be triggered by either pushing a commit that changes the `Dockerfile`, 
# or manually dispatching the workflow.

name: Publish Docker image (Base R)

on: 
  workflow_dispatch:
  push: 
    paths: 
      - 'base-r/Dockerfile'
      
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.meta.outputs.version }} # expose tag for downstream job
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ubcmds/base-r
          tags: |
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./base-r
          file: base-r/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Save tag for downstream
        run: echo "TAG=${{ steps.meta.outputs.version }}" >> $GITHUB_ENV

