name: Update R Course Images

on:
  workflow_run:
    workflows: ["Publish Docker image (Base R)"]
    types:
      - completed

jobs:
  update-dependents:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4

      # ⬇ Download the artifact from Workflow 1
      - name: Download base-r tag artifact
        uses: actions/download-artifact@v4
        with:
          name: base-r-tag
          path: ./artifacts

      - name: Load tag into env
        run: echo "NEW_TAG=$(cat ./artifacts/image-tag.txt)" >> $GITHUB_ENV

      # ⬇ Update dependent Dockerfiles
      - name: Update Dockerfiles
        run: |
          echo "Updating Dockerfiles with tag ${NEW_TAG}"
          grep -rl --exclude-dir=".git" "ubcmds/base-r:" . \
            | xargs sed -i "s|ubcmds/base-r:[a-zA-Z0-9._-]\+|ubcmds/base-r:${NEW_TAG}|g"

      # ⬇ Commit & PR
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: bump base-r to ${{ env.NEW_TAG }}"
          branch: update/base-r-${{ env.NEW_TAG }}
          title: "Update base-r to ${{ env.NEW_TAG }}"
          body: |
            This PR updates all Dockerfiles in the repo that reference `ubcmds/base-r` 
            to use the newly published tag `${{ env.NEW_TAG }}`.
